config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'boards#index'

    resources :boards do
      resources :tasks
    end

    resources :tasks do
      resources :comments, only: [:new, :create]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 30 }
  validates :title, format: {  with: /\A(?!\@)/ }

  validates :content, presence: true
  validates :content, length: { minimum: 10 }
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  belongs_to :user
  has_many :tasks, dependent: :destroy

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    errors.add(:content, '40字以上記入してください') unless char_count > 40
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  limit      :date
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  belongs_to :user
  belongs_to :board

  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def display_name
    self.email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show 
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.build(board_params)
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    task = Task.find(params[:task_id])
    @comment = task.comments.build
  end

  def create
    task = Task.find(params[:task_id])
    @comment = task.comments.build(comment_params.merge(user_id: current_user.id))
    if @comment.save
      redirect_to board_task_path(board_id: task.board_id, id: task.id), notice: 'コメントを追加しました'
    else
      flash.now[:error] = 'コメントを追加できませんでした'
      render :new
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @task = Task.all
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params.merge!(user_id: current_user.id))
    if @task.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def show
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    @comments = @task.comments
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :limit, :eyecatch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.haml
= link_to board_path(board) do
  .card
    .card_title= board.title
    .card_content= board.content
    .card_icon
      = image_tag 'Oval.png'
    %p= board.author_name 
    %p= board.display_created_at
    .card_detail
      = image_tag 'Combined Shape'

app/views/boards/_form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h1 All boards
  - @boards.each do |board|
    = render 'board', board: board
  .add_new_bord
    = link_to new_board_path do
      %p +Add new board

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.card
  .card_title= @board.title
  .card_content= @board.content
  .card_icon
    = image_tag 'Oval.png'
  %p= @board.author_name
  %p= @board.display_created_at
  - if user_signed_in? && current_user.has_written?(@board)
    .card_detail
      .dropdown
        = image_tag 'Combined Shape', class:"dropbtn"
        .dropdown-content
          = link_to '編集',edit_board_path(@board)
          = link_to '削除', board_path(@board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }

  - @tasks.each do |task|
    = render 'commons/task', task: task 


.container  
  = link_to '+Add new card', new_board_task_path(@board)

app/views/comments/new.html.haml
.container  New Comment
  
= form_with(model: @comment, url: task_comments_path(@comment.task), local: true) do |f|
  %div
    =f.text_area :content
  = f.submit 'Submit', class: 'btn-primary'

app/views/commons/_task.html.haml
.card
  = link_to board_task_path(board_id: @board.id, id: task.id) do
    .task_title
      = task.title
    .task_content
      = task.content
    .task_limit
      = task.limit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Taskapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header
      .container.clear
        - if !current_page?(root_path)
          = link_to boards_path do
            %div
              %p Boards
        - else
          %div
            %p Boards
        - if user_signed_in?
          .header-right
            = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
        -else
          = link_to 'ログイン', new_user_password_path
        .line
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'Image'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :limit, 'Dedline'
    %div
      = f.date_field :limit

    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.task_title
  = @task.title
.task_content
  = @task.content
.task_limit
  = @task.limit
.task_eyecatch
  = image_tag @task.eyecatch
%h1 Comment
- @comments.each do |comment|
  %div
    = comment.content

.container
  = link_to 'Add new comment', new_task_comment_path(@task)